apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb-server
  namespace: broker-test
  labels:
    app: mariadb-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-server
    spec:
      containers:
      - name: mariadb-server
        image: mariadb:10.1.16
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-server
  namespace: broker-test
spec:
  ports:
  - name: mariadb-server
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb-server
